# Generated by Django 2.1.4 on 2019-10-06 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('url', models.CharField(max_length=155)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('pic', models.CharField(max_length=255, verbose_name='用户头像')),
                ('level', models.IntegerField(default=0, verbose_name='用户类型，0普通用户，1普通会员，2高级会员')),
                ('is_active', models.IntegerField(default=0, verbose_name='激活状态，0未激活，1激活')),
                ('integral', models.IntegerField(default=0, verbose_name='积分')),
                ('invitation_code', models.CharField(default='', max_length=50, verbose_name='邀请码')),
                ('token', models.CharField(max_length=255, verbose_name='用户登录生成的token')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'userlevel',
            },
        ),
        migrations.CreateModel(
            name='UserLevelCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(verbose_name='时长')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.UserLevel', verbose_name='关联等级表ID')),
            ],
            options={
                'db_table': 'userlevelcondition',
            },
        ),
        migrations.AddField(
            model_name='resources',
            name='roles',
            field=models.ManyToManyField(related_name='resources', to='edu.Roles'),
        ),
        migrations.AddField(
            model_name='admin',
            name='roles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Roles'),
        ),
    ]
