# Generated by Django 2.1.4 on 2019-09-26 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'userlevel',
            },
        ),
        migrations.CreateModel(
            name='UserLevelCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='时长')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.UserLevel', verbose_name='关联等级表ID')),
            ],
            options={
                'db_table': 'userlevelcondition',
            },
        ),
    ]
