# Generated by Django 2.1.5 on 2019-10-11 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('count', models.IntegerField()),
                ('type', models.IntegerField()),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('condition', models.DecimalField(decimal_places=2, max_digits=7)),
                ('integral', models.IntegerField()),
                ('money', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='课程标题')),
                ('pic', models.CharField(max_length=255, verbose_name='课程图片')),
                ('info', models.CharField(max_length=255, verbose_name='课程简介')),
                ('online', models.IntegerField(default=0, verbose_name='是否上线0没上线,1上线')),
                ('member', models.IntegerField(default=0, verbose_name='是否会员，0非会员,1会员,2训练营')),
                ('attention', models.IntegerField(default=0, verbose_name='关注量')),
                ('learn', models.IntegerField(default=0, verbose_name='学过人数')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论数量')),
                ('recommand', models.CharField(max_length=50, verbose_name='推荐课程，0是1否')),
                ('detail', models.CharField(max_length=200, verbose_name='课程详情')),
                ('section_num', models.IntegerField(default=0, verbose_name='章节数')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.CharField(max_length=50, verbose_name='路径图片')),
                ('path', models.CharField(max_length=255, verbose_name='路径名称')),
                ('info', models.CharField(max_length=255, verbose_name='路径简介')),
                ('studynum', models.IntegerField(default=0, verbose_name='学习人数')),
            ],
            options={
                'db_table': 'path',
            },
        ),
        migrations.CreateModel(
            name='Path_stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=50, verbose_name='阶段名称')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Path', verbose_name='关联路径')),
            ],
            options={
                'db_table': 'path_stage',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(max_length=50, verbose_name='折扣')),
                ('pre_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='原价格')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='折扣后价格')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Course', verbose_name='关联课程')),
            ],
            options={
                'db_table': 'price',
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('url', models.CharField(max_length=155)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50, verbose_name='课程章节名称')),
                ('video', models.CharField(max_length=50, verbose_name='视频链接')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Course', verbose_name='关联课程')),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='姓名')),
                ('describe', models.CharField(max_length=255, verbose_name='讲师描述')),
                ('pic', models.CharField(max_length=255, verbose_name='头像')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdPartyLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, verbose_name='第三方登录平台返回的唯一uid')),
                ('login_type', models.IntegerField(default=0, verbose_name='0微博，1微信，2qq')),
            ],
            options={
                'db_table': 'thridpartylogin',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20, null=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('pic', models.CharField(default='', max_length=255, null=True, verbose_name='用户头像')),
                ('is_active', models.IntegerField(default=0, verbose_name='激活状态，0未激活，1激活')),
                ('integral', models.IntegerField(default=0, verbose_name='积分')),
                ('invitation_code', models.CharField(default='', max_length=50, null=True, verbose_name='邀请码')),
                ('token', models.CharField(default='', max_length=255, null=True, verbose_name='用户登录生成的token')),
                ('email', models.CharField(max_length=255, verbose_name='邮箱')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'userlevel',
            },
        ),
        migrations.CreateModel(
            name='UserLevelCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(verbose_name='时长')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.UserLevel', verbose_name='关联等级表ID')),
            ],
            options={
                'db_table': 'userlevelcondition',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.UserLevel', verbose_name='用户类型，0普通用户，1普通会员，2高级会员'),
        ),
        migrations.AddField(
            model_name='thirdpartylogin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.User', verbose_name='关联用户ID'),
        ),
        migrations.AddField(
            model_name='resources',
            name='roles',
            field=models.ManyToManyField(related_name='resources', to='edu.Roles'),
        ),
        migrations.AddField(
            model_name='price',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.UserLevel', verbose_name='类型0普通,1会员,2高级会员'),
        ),
        migrations.AddField(
            model_name='course',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Path', verbose_name='所属路径'),
        ),
        migrations.AddField(
            model_name='course',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Path_stage', verbose_name='关联阶段'),
        ),
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Tag', verbose_name='关联标签'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Teacher', verbose_name='关联老师'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.Course'),
        ),
        migrations.AddField(
            model_name='admin',
            name='roles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Roles'),
        ),
    ]
