# Generated by Django 2.1.4 on 2019-10-07 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='课程标题')),
                ('pic', models.CharField(max_length=255, verbose_name='课程图片')),
                ('info', models.CharField(max_length=255, verbose_name='课程简介')),
                ('online', models.IntegerField(default=0, verbose_name='是否上线0没上线,1上线')),
                ('member', models.IntegerField(default=0, verbose_name='是否会员，0非会员,1会员,2训练营')),
                ('attention', models.IntegerField(default=0, verbose_name='关注量')),
                ('learn', models.IntegerField(default=0, verbose_name='学过人数')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论数量')),
                ('recommand', models.CharField(max_length=50, verbose_name='推荐课程')),
                ('detail', models.CharField(max_length=200, verbose_name='课程详情')),
                ('section_num', models.IntegerField(default=0, verbose_name='章节数')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.CharField(max_length=50, verbose_name='路径图片')),
                ('path', models.CharField(max_length=255, verbose_name='路径名称')),
                ('info', models.CharField(max_length=255, verbose_name='路径简介')),
                ('studynum', models.IntegerField(default=0, verbose_name='学习人数')),
            ],
            options={
                'db_table': 'path',
            },
        ),
        migrations.CreateModel(
            name='Path_stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=50, verbose_name='阶段名称')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Path', verbose_name='关联路径')),
            ],
            options={
                'db_table': 'path_stage',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50, verbose_name='课程章节名称')),
                ('video', models.CharField(max_length=50, verbose_name='视频链接')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Course', verbose_name='关联课程')),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='姓名')),
                ('describe', models.CharField(max_length=255, verbose_name='讲师描述')),
                ('pic', models.CharField(max_length=255, verbose_name='头像')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Path_stage', verbose_name='关联阶段'),
        ),
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Tag', verbose_name='关联标签'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Teacher', verbose_name='关联老师'),
        ),
    ]
