# Generated by Django 2.1.4 on 2019-10-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.CharField(default='', max_length=255, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='', max_length=255, verbose_name='用户登录生成的token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=20, verbose_name='用户名'),
        ),
    ]
