# Generated by Django 2.1.4 on 2019-10-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_auto_20191010_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invitation_code',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='邀请码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='用户登录生成的token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='用户名'),
        ),
    ]
