# Generated by Django 2.1.4 on 2019-10-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_auto_20191007_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='path',
            new_name='stage',
        ),
        migrations.AddField(
            model_name='course',
            name='path_id',
            field=models.IntegerField(default=0, verbose_name='所属路径'),
        ),
    ]
