# Generated by Django 2.1.4 on 2019-09-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_auto_20190927_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
