# Generated by Django 2.1.4 on 2019-09-27 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_auto_20190927_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles_resources',
            name='resources_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edu.Resources'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roles_resources',
            name='roles_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='edu.Roles'),
            preserve_default=False,
        ),
    ]
