# Generated by Django 2.1.5 on 2019-10-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_auto_20191012_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='video',
            field=models.CharField(max_length=255, verbose_name='视频链接'),
        ),
    ]
