# Generated by Django 2.1.4 on 2019-09-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0005_auto_20190927_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles_resources',
            old_name='resources_id',
            new_name='resources',
        ),
        migrations.RenameField(
            model_name='roles_resources',
            old_name='roles_id',
            new_name='roles',
        ),
    ]
