# Generated by Django 2.1.5 on 2019-10-14 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0005_auto_20191012_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_title', models.CharField(max_length=50, verbose_name='问答标题')),
                ('answer_content', models.CharField(max_length=255, verbose_name='问答内容')),
                ('browse_id', models.IntegerField(verbose_name='浏览量')),
                ('pid', models.IntegerField(verbose_name='上一级评论')),
                ('top', models.IntegerField(verbose_name='顶级评论')),
                ('type', models.IntegerField(verbose_name='自身级别评论')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Course', verbose_name='课程id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.User', verbose_name='用户id')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('pid', models.IntegerField(verbose_name='上一级评论id')),
                ('top', models.IntegerField(verbose_name='顶级评论')),
                ('type_ud', models.IntegerField(verbose_name='自身级别id')),
                ('course', models.IntegerField(verbose_name='查询评论id')),
                ('comment_type', models.IntegerField(default=0, verbose_name='评论类型')),
                ('status', models.IntegerField(default=0, verbose_name='审核状态，0否1是')),
                ('reason', models.CharField(max_length=255, verbose_name='失败原因')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.User', verbose_name='用户id')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_content', models.CharField(max_length=255, verbose_name='报告内容')),
                ('report_title', models.CharField(max_length=255, verbose_name='报告标题')),
                ('report_browse', models.IntegerField(verbose_name='实验报告浏览量')),
                ('linknum', models.IntegerField(verbose_name='点赞数')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Course', verbose_name='课程id')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Section', verbose_name='章节id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.User', verbose_name='用户id')),
            ],
        ),
    ]
