# Generated by Django 2.1.5 on 2019-10-14 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_answer_comment_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integral_coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_order', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('coupon_money', models.DecimalField(decimal_places=2, max_digits=7)),
                ('max_money', models.DecimalField(decimal_places=2, max_digits=7)),
                ('type', models.IntegerField()),
                ('status', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.User')),
            ],
        ),
        migrations.CreateModel(
            name='rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.FloatField(default=0.01)),
                ('min_integral', models.IntegerField(default=100)),
                ('max_integral', models.IntegerField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='User_path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.Path')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.User')),
            ],
        ),
    ]
