# Generated by Django 2.1.4 on 2019-10-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0007_integral_coupon_rule_user_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invitation_coded',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='被邀请码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='invitation_code',
            field=models.CharField(default=1, max_length=50, verbose_name='邀请码'),
            preserve_default=False,
        ),
    ]
