# Generated by Django 2.1.4 on 2019-10-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0008_auto_20191015_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invitation_code',
            field=models.CharField(max_length=255, verbose_name='邀请码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='invitation_coded',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='被邀请码'),
        ),
    ]
