# Generated by Django 2.1.4 on 2019-10-15 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0009_auto_20191015_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(max_length=255, verbose_name='订单号')),
                ('level', models.IntegerField(default=0, verbose_name='1普通会员，2高级会员')),
                ('status', models.IntegerField(default=0, verbose_name='支付状态')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='总价')),
                ('type', models.IntegerField(default=0, verbose_name='支付方式，0支付宝，1微信')),
                ('serial_number', models.CharField(default='', max_length=255, verbose_name='支付流水号')),
                ('time', models.IntegerField(default=0, verbose_name='会员时长')),
                ('code', models.CharField(default='', max_length=50, verbose_name='邀请码，如果是通过别人的邀请码开通的会员，则填对应邀请码')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.User', verbose_name='关联用户ID')),
            ],
            options={
                'db_table': 'memberorder',
            },
        ),
    ]
