# Generated by Django 2.1.4 on 2019-10-16 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0010_memberorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, verbose_name='0普通会员，1高级会员')),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.User', verbose_name='关联用户ID')),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.AlterField(
            model_name='memberorder',
            name='status',
            field=models.IntegerField(default=0, verbose_name='支付状态 0未支付 1已支付 '),
        ),
    ]
