# Generated by Django 2.1.4 on 2019-10-16 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0011_auto_20191016_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('pyt_type', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pay_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('preferential_way', models.IntegerField()),
                ('preferential_money', models.DecimalField(decimal_places=2, max_digits=7)),
                ('order_status', models.IntegerField()),
                ('code', models.CharField(max_length=100)),
                ('coupon', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.User')),
            ],
        ),
        migrations.AlterField(
            model_name='memberorder',
            name='level',
            field=models.IntegerField(default=0, verbose_name='2普通会员，3高级会员'),
        ),
    ]
