# Generated by Django 2.1.4 on 2019-10-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0012_auto_20191016_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours_order',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cours_order',
            name='coupon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
