# Generated by Django 2.1.4 on 2019-10-16 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0013_auto_20191016_1706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rule',
            new_name='Rules',
        ),
    ]
