# Generated by Django 2.1.4 on 2019-10-18 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0014_auto_20191016_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('data', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'act',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url', models.CharField(max_length=100)),
                ('pic', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
                ('is_show', models.IntegerField(default=1)),
                ('sort', models.IntegerField()),
            ],
            options={
                'db_table': 'banner',
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('find_id', models.IntegerField(verbose_name='寻找对应id')),
                ('collect_type', models.IntegerField(default=0, verbose_name='收藏类型0实验报告1实验问答')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.User', verbose_name='用户id')),
            ],
            options={
                'db_table': 'collect',
            },
        ),
        migrations.CreateModel(
            name='Coupon_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_integral', models.IntegerField(default=0, verbose_name='1增加，2减少')),
                ('s_integral', models.IntegerField(default=0)),
                ('before_integral', models.IntegerField(default=0)),
                ('end_integral', models.IntegerField(default=0)),
                ('effect', models.IntegerField(default=0, verbose_name='1抵消金额，2优惠券')),
                ('coupon_code', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.User')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.User')),
            ],
            options={
                'db_table': 'course_collect',
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('count', models.IntegerField()),
                ('types', models.IntegerField(default=0, verbose_name='1首次,2全场,3指定商品,4指定会员')),
                ('course_id', models.IntegerField(default=0, verbose_name='类型为3时指定课程')),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField()),
                ('condition', models.DecimalField(decimal_places=2, max_digits=7)),
                ('money', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'db_table': 'forum',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(max_length=155)),
                ('result', models.IntegerField(default=0, verbose_name='0失败，1成功')),
                ('reason', models.CharField(max_length=155)),
                ('admin_id', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='Roles_Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Resources')),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Roles')),
            ],
            options={
                'db_table': 'roles_resources',
            },
        ),
        migrations.CreateModel(
            name='SiteMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='站内信息标题')),
                ('content', models.TextField(verbose_name='站内信息内容')),
            ],
            options={
                'db_table': 'sitemessage',
            },
        ),
        migrations.CreateModel(
            name='Sk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('act', models.ForeignKey(on_delete=True, to='edu.Act')),
                ('course', models.ForeignKey(on_delete=True, to='edu.Course')),
            ],
            options={
                'db_table': 'sk',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now=True)),
                ('end', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'time',
            },
        ),
        migrations.CreateModel(
            name='User_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.Course')),
                ('section_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.Section')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.User')),
            ],
            options={
                'db_table': 'user_course',
            },
        ),
        migrations.CreateModel(
            name='UserSiteMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(verbose_name='状态，0未读，1已读')),
                ('SiteMessage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.SiteMessage', verbose_name='外键关联站内信息表')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.User', verbose_name='外键关联用户ID')),
            ],
            options={
                'db_table': 'usersitemessage',
            },
        ),
        migrations.CreateModel(
            name='UserTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Teacher', verbose_name='课程id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.User', verbose_name='用户id')),
            ],
            options={
                'db_table': 'userteacher',
            },
        ),
        migrations.CreateModel(
            name='Work_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('problem', models.CharField(max_length=155)),
                ('content', models.CharField(max_length=155)),
                ('pid', models.CharField(max_length=155)),
                ('status', models.IntegerField(default=0, verbose_name='0未处理，1处理')),
            ],
            options={
                'db_table': 'work_order',
            },
        ),
        migrations.AddField(
            model_name='sk',
            name='time',
            field=models.ForeignKey(on_delete=True, to='edu.Time'),
        ),
    ]
