# Generated by Django 2.1.4 on 2019-10-18 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0017_auto_20191018_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=1)),
                ('money', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.User')),
            ],
        ),
        migrations.AddField(
            model_name='time',
            name='act',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edu.Act'),
            preserve_default=False,
        ),
    ]
