# Generated by Django 2.1.4 on 2019-10-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0018_auto_20191018_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='data',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='end',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='start',
            field=models.TimeField(auto_now=True),
        ),
    ]
