# Generated by Django 2.1.4 on 2019-10-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0019_auto_20191020_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actorder',
            name='start_time',
        ),
    ]
